// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_all.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_test_5fall_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_test_5fall_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_test_5fall_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_test_5fall_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_test_5fall_2eproto;
class addtestRequest;
struct addtestRequestDefaultTypeInternal;
extern addtestRequestDefaultTypeInternal _addtestRequest_default_instance_;
class addtestResponse;
struct addtestResponseDefaultTypeInternal;
extern addtestResponseDefaultTypeInternal _addtestResponse_default_instance_;
class querytestRequest;
struct querytestRequestDefaultTypeInternal;
extern querytestRequestDefaultTypeInternal _querytestRequest_default_instance_;
class querytestResponse;
struct querytestResponseDefaultTypeInternal;
extern querytestResponseDefaultTypeInternal _querytestResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::addtestRequest* Arena::CreateMaybeMessage<::addtestRequest>(Arena*);
template<> ::addtestResponse* Arena::CreateMaybeMessage<::addtestResponse>(Arena*);
template<> ::querytestRequest* Arena::CreateMaybeMessage<::querytestRequest>(Arena*);
template<> ::querytestResponse* Arena::CreateMaybeMessage<::querytestResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class addtestRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:addtestRequest) */ {
 public:
  inline addtestRequest() : addtestRequest(nullptr) {}
  ~addtestRequest() override;
  explicit PROTOBUF_CONSTEXPR addtestRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  addtestRequest(const addtestRequest& from);
  addtestRequest(addtestRequest&& from) noexcept
    : addtestRequest() {
    *this = ::std::move(from);
  }

  inline addtestRequest& operator=(const addtestRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline addtestRequest& operator=(addtestRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const addtestRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const addtestRequest* internal_default_instance() {
    return reinterpret_cast<const addtestRequest*>(
               &_addtestRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(addtestRequest& a, addtestRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(addtestRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(addtestRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  addtestRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<addtestRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const addtestRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const addtestRequest& from) {
    addtestRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(addtestRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "addtestRequest";
  }
  protected:
  explicit addtestRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGoodsFieldNumber = 2,
    kPriceFieldNumber = 1,
  };
  // string goods = 2;
  void clear_goods();
  const std::string& goods() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_goods(ArgT0&& arg0, ArgT... args);
  std::string* mutable_goods();
  PROTOBUF_NODISCARD std::string* release_goods();
  void set_allocated_goods(std::string* goods);
  private:
  const std::string& _internal_goods() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_goods(const std::string& value);
  std::string* _internal_mutable_goods();
  public:

  // int32 price = 1;
  void clear_price();
  int32_t price() const;
  void set_price(int32_t value);
  private:
  int32_t _internal_price() const;
  void _internal_set_price(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:addtestRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr goods_;
    int32_t price_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_5fall_2eproto;
};
// -------------------------------------------------------------------

class addtestResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:addtestResponse) */ {
 public:
  inline addtestResponse() : addtestResponse(nullptr) {}
  ~addtestResponse() override;
  explicit PROTOBUF_CONSTEXPR addtestResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  addtestResponse(const addtestResponse& from);
  addtestResponse(addtestResponse&& from) noexcept
    : addtestResponse() {
    *this = ::std::move(from);
  }

  inline addtestResponse& operator=(const addtestResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline addtestResponse& operator=(addtestResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const addtestResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const addtestResponse* internal_default_instance() {
    return reinterpret_cast<const addtestResponse*>(
               &_addtestResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(addtestResponse& a, addtestResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(addtestResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(addtestResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  addtestResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<addtestResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const addtestResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const addtestResponse& from) {
    addtestResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(addtestResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "addtestResponse";
  }
  protected:
  explicit addtestResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResInfoFieldNumber = 2,
    kOrderIdFieldNumber = 3,
    kRetCodeFieldNumber = 1,
  };
  // string res_info = 2;
  void clear_res_info();
  const std::string& res_info() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_res_info(ArgT0&& arg0, ArgT... args);
  std::string* mutable_res_info();
  PROTOBUF_NODISCARD std::string* release_res_info();
  void set_allocated_res_info(std::string* res_info);
  private:
  const std::string& _internal_res_info() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_res_info(const std::string& value);
  std::string* _internal_mutable_res_info();
  public:

  // string order_id = 3;
  void clear_order_id();
  const std::string& order_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_order_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_order_id();
  PROTOBUF_NODISCARD std::string* release_order_id();
  void set_allocated_order_id(std::string* order_id);
  private:
  const std::string& _internal_order_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_order_id(const std::string& value);
  std::string* _internal_mutable_order_id();
  public:

  // int32 ret_code = 1;
  void clear_ret_code();
  int32_t ret_code() const;
  void set_ret_code(int32_t value);
  private:
  int32_t _internal_ret_code() const;
  void _internal_set_ret_code(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:addtestResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr res_info_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr order_id_;
    int32_t ret_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_5fall_2eproto;
};
// -------------------------------------------------------------------

class querytestRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:querytestRequest) */ {
 public:
  inline querytestRequest() : querytestRequest(nullptr) {}
  ~querytestRequest() override;
  explicit PROTOBUF_CONSTEXPR querytestRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  querytestRequest(const querytestRequest& from);
  querytestRequest(querytestRequest&& from) noexcept
    : querytestRequest() {
    *this = ::std::move(from);
  }

  inline querytestRequest& operator=(const querytestRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline querytestRequest& operator=(querytestRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const querytestRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const querytestRequest* internal_default_instance() {
    return reinterpret_cast<const querytestRequest*>(
               &_querytestRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(querytestRequest& a, querytestRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(querytestRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(querytestRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  querytestRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<querytestRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const querytestRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const querytestRequest& from) {
    querytestRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(querytestRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "querytestRequest";
  }
  protected:
  explicit querytestRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderIdFieldNumber = 1,
  };
  // string order_id = 1;
  void clear_order_id();
  const std::string& order_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_order_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_order_id();
  PROTOBUF_NODISCARD std::string* release_order_id();
  void set_allocated_order_id(std::string* order_id);
  private:
  const std::string& _internal_order_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_order_id(const std::string& value);
  std::string* _internal_mutable_order_id();
  public:

  // @@protoc_insertion_point(class_scope:querytestRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr order_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_5fall_2eproto;
};
// -------------------------------------------------------------------

class querytestResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:querytestResponse) */ {
 public:
  inline querytestResponse() : querytestResponse(nullptr) {}
  ~querytestResponse() override;
  explicit PROTOBUF_CONSTEXPR querytestResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  querytestResponse(const querytestResponse& from);
  querytestResponse(querytestResponse&& from) noexcept
    : querytestResponse() {
    *this = ::std::move(from);
  }

  inline querytestResponse& operator=(const querytestResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline querytestResponse& operator=(querytestResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const querytestResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const querytestResponse* internal_default_instance() {
    return reinterpret_cast<const querytestResponse*>(
               &_querytestResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(querytestResponse& a, querytestResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(querytestResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(querytestResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  querytestResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<querytestResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const querytestResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const querytestResponse& from) {
    querytestResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(querytestResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "querytestResponse";
  }
  protected:
  explicit querytestResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResInfoFieldNumber = 2,
    kOrderIdFieldNumber = 3,
    kGoodsFieldNumber = 5,
    kRetCodeFieldNumber = 1,
    kPriceFieldNumber = 4,
  };
  // string res_info = 2;
  void clear_res_info();
  const std::string& res_info() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_res_info(ArgT0&& arg0, ArgT... args);
  std::string* mutable_res_info();
  PROTOBUF_NODISCARD std::string* release_res_info();
  void set_allocated_res_info(std::string* res_info);
  private:
  const std::string& _internal_res_info() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_res_info(const std::string& value);
  std::string* _internal_mutable_res_info();
  public:

  // string order_id = 3;
  void clear_order_id();
  const std::string& order_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_order_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_order_id();
  PROTOBUF_NODISCARD std::string* release_order_id();
  void set_allocated_order_id(std::string* order_id);
  private:
  const std::string& _internal_order_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_order_id(const std::string& value);
  std::string* _internal_mutable_order_id();
  public:

  // string goods = 5;
  void clear_goods();
  const std::string& goods() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_goods(ArgT0&& arg0, ArgT... args);
  std::string* mutable_goods();
  PROTOBUF_NODISCARD std::string* release_goods();
  void set_allocated_goods(std::string* goods);
  private:
  const std::string& _internal_goods() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_goods(const std::string& value);
  std::string* _internal_mutable_goods();
  public:

  // int32 ret_code = 1;
  void clear_ret_code();
  int32_t ret_code() const;
  void set_ret_code(int32_t value);
  private:
  int32_t _internal_ret_code() const;
  void _internal_set_ret_code(int32_t value);
  public:

  // int32 price = 4;
  void clear_price();
  int32_t price() const;
  void set_price(int32_t value);
  private:
  int32_t _internal_price() const;
  void _internal_set_price(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:querytestResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr res_info_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr order_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr goods_;
    int32_t ret_code_;
    int32_t price_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_5fall_2eproto;
};
// ===================================================================

class TestService_Stub;

class TestService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline TestService() {};
 public:
  virtual ~TestService();

  typedef TestService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void add_test(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::addtestRequest* request,
                       ::addtestResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void query_test(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::querytestRequest* request,
                       ::querytestResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(TestService);
};

class TestService_Stub : public TestService {
 public:
  TestService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  TestService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~TestService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements TestService ------------------------------------------

  void add_test(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::addtestRequest* request,
                       ::addtestResponse* response,
                       ::google::protobuf::Closure* done);
  void query_test(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::querytestRequest* request,
                       ::querytestResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(TestService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// addtestRequest

// int32 price = 1;
inline void addtestRequest::clear_price() {
  _impl_.price_ = 0;
}
inline int32_t addtestRequest::_internal_price() const {
  return _impl_.price_;
}
inline int32_t addtestRequest::price() const {
  // @@protoc_insertion_point(field_get:addtestRequest.price)
  return _internal_price();
}
inline void addtestRequest::_internal_set_price(int32_t value) {
  
  _impl_.price_ = value;
}
inline void addtestRequest::set_price(int32_t value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:addtestRequest.price)
}

// string goods = 2;
inline void addtestRequest::clear_goods() {
  _impl_.goods_.ClearToEmpty();
}
inline const std::string& addtestRequest::goods() const {
  // @@protoc_insertion_point(field_get:addtestRequest.goods)
  return _internal_goods();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void addtestRequest::set_goods(ArgT0&& arg0, ArgT... args) {
 
 _impl_.goods_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:addtestRequest.goods)
}
inline std::string* addtestRequest::mutable_goods() {
  std::string* _s = _internal_mutable_goods();
  // @@protoc_insertion_point(field_mutable:addtestRequest.goods)
  return _s;
}
inline const std::string& addtestRequest::_internal_goods() const {
  return _impl_.goods_.Get();
}
inline void addtestRequest::_internal_set_goods(const std::string& value) {
  
  _impl_.goods_.Set(value, GetArenaForAllocation());
}
inline std::string* addtestRequest::_internal_mutable_goods() {
  
  return _impl_.goods_.Mutable(GetArenaForAllocation());
}
inline std::string* addtestRequest::release_goods() {
  // @@protoc_insertion_point(field_release:addtestRequest.goods)
  return _impl_.goods_.Release();
}
inline void addtestRequest::set_allocated_goods(std::string* goods) {
  if (goods != nullptr) {
    
  } else {
    
  }
  _impl_.goods_.SetAllocated(goods, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.goods_.IsDefault()) {
    _impl_.goods_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:addtestRequest.goods)
}

// -------------------------------------------------------------------

// addtestResponse

// int32 ret_code = 1;
inline void addtestResponse::clear_ret_code() {
  _impl_.ret_code_ = 0;
}
inline int32_t addtestResponse::_internal_ret_code() const {
  return _impl_.ret_code_;
}
inline int32_t addtestResponse::ret_code() const {
  // @@protoc_insertion_point(field_get:addtestResponse.ret_code)
  return _internal_ret_code();
}
inline void addtestResponse::_internal_set_ret_code(int32_t value) {
  
  _impl_.ret_code_ = value;
}
inline void addtestResponse::set_ret_code(int32_t value) {
  _internal_set_ret_code(value);
  // @@protoc_insertion_point(field_set:addtestResponse.ret_code)
}

// string res_info = 2;
inline void addtestResponse::clear_res_info() {
  _impl_.res_info_.ClearToEmpty();
}
inline const std::string& addtestResponse::res_info() const {
  // @@protoc_insertion_point(field_get:addtestResponse.res_info)
  return _internal_res_info();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void addtestResponse::set_res_info(ArgT0&& arg0, ArgT... args) {
 
 _impl_.res_info_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:addtestResponse.res_info)
}
inline std::string* addtestResponse::mutable_res_info() {
  std::string* _s = _internal_mutable_res_info();
  // @@protoc_insertion_point(field_mutable:addtestResponse.res_info)
  return _s;
}
inline const std::string& addtestResponse::_internal_res_info() const {
  return _impl_.res_info_.Get();
}
inline void addtestResponse::_internal_set_res_info(const std::string& value) {
  
  _impl_.res_info_.Set(value, GetArenaForAllocation());
}
inline std::string* addtestResponse::_internal_mutable_res_info() {
  
  return _impl_.res_info_.Mutable(GetArenaForAllocation());
}
inline std::string* addtestResponse::release_res_info() {
  // @@protoc_insertion_point(field_release:addtestResponse.res_info)
  return _impl_.res_info_.Release();
}
inline void addtestResponse::set_allocated_res_info(std::string* res_info) {
  if (res_info != nullptr) {
    
  } else {
    
  }
  _impl_.res_info_.SetAllocated(res_info, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.res_info_.IsDefault()) {
    _impl_.res_info_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:addtestResponse.res_info)
}

// string order_id = 3;
inline void addtestResponse::clear_order_id() {
  _impl_.order_id_.ClearToEmpty();
}
inline const std::string& addtestResponse::order_id() const {
  // @@protoc_insertion_point(field_get:addtestResponse.order_id)
  return _internal_order_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void addtestResponse::set_order_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.order_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:addtestResponse.order_id)
}
inline std::string* addtestResponse::mutable_order_id() {
  std::string* _s = _internal_mutable_order_id();
  // @@protoc_insertion_point(field_mutable:addtestResponse.order_id)
  return _s;
}
inline const std::string& addtestResponse::_internal_order_id() const {
  return _impl_.order_id_.Get();
}
inline void addtestResponse::_internal_set_order_id(const std::string& value) {
  
  _impl_.order_id_.Set(value, GetArenaForAllocation());
}
inline std::string* addtestResponse::_internal_mutable_order_id() {
  
  return _impl_.order_id_.Mutable(GetArenaForAllocation());
}
inline std::string* addtestResponse::release_order_id() {
  // @@protoc_insertion_point(field_release:addtestResponse.order_id)
  return _impl_.order_id_.Release();
}
inline void addtestResponse::set_allocated_order_id(std::string* order_id) {
  if (order_id != nullptr) {
    
  } else {
    
  }
  _impl_.order_id_.SetAllocated(order_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.order_id_.IsDefault()) {
    _impl_.order_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:addtestResponse.order_id)
}

// -------------------------------------------------------------------

// querytestRequest

// string order_id = 1;
inline void querytestRequest::clear_order_id() {
  _impl_.order_id_.ClearToEmpty();
}
inline const std::string& querytestRequest::order_id() const {
  // @@protoc_insertion_point(field_get:querytestRequest.order_id)
  return _internal_order_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void querytestRequest::set_order_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.order_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:querytestRequest.order_id)
}
inline std::string* querytestRequest::mutable_order_id() {
  std::string* _s = _internal_mutable_order_id();
  // @@protoc_insertion_point(field_mutable:querytestRequest.order_id)
  return _s;
}
inline const std::string& querytestRequest::_internal_order_id() const {
  return _impl_.order_id_.Get();
}
inline void querytestRequest::_internal_set_order_id(const std::string& value) {
  
  _impl_.order_id_.Set(value, GetArenaForAllocation());
}
inline std::string* querytestRequest::_internal_mutable_order_id() {
  
  return _impl_.order_id_.Mutable(GetArenaForAllocation());
}
inline std::string* querytestRequest::release_order_id() {
  // @@protoc_insertion_point(field_release:querytestRequest.order_id)
  return _impl_.order_id_.Release();
}
inline void querytestRequest::set_allocated_order_id(std::string* order_id) {
  if (order_id != nullptr) {
    
  } else {
    
  }
  _impl_.order_id_.SetAllocated(order_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.order_id_.IsDefault()) {
    _impl_.order_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:querytestRequest.order_id)
}

// -------------------------------------------------------------------

// querytestResponse

// int32 ret_code = 1;
inline void querytestResponse::clear_ret_code() {
  _impl_.ret_code_ = 0;
}
inline int32_t querytestResponse::_internal_ret_code() const {
  return _impl_.ret_code_;
}
inline int32_t querytestResponse::ret_code() const {
  // @@protoc_insertion_point(field_get:querytestResponse.ret_code)
  return _internal_ret_code();
}
inline void querytestResponse::_internal_set_ret_code(int32_t value) {
  
  _impl_.ret_code_ = value;
}
inline void querytestResponse::set_ret_code(int32_t value) {
  _internal_set_ret_code(value);
  // @@protoc_insertion_point(field_set:querytestResponse.ret_code)
}

// string res_info = 2;
inline void querytestResponse::clear_res_info() {
  _impl_.res_info_.ClearToEmpty();
}
inline const std::string& querytestResponse::res_info() const {
  // @@protoc_insertion_point(field_get:querytestResponse.res_info)
  return _internal_res_info();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void querytestResponse::set_res_info(ArgT0&& arg0, ArgT... args) {
 
 _impl_.res_info_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:querytestResponse.res_info)
}
inline std::string* querytestResponse::mutable_res_info() {
  std::string* _s = _internal_mutable_res_info();
  // @@protoc_insertion_point(field_mutable:querytestResponse.res_info)
  return _s;
}
inline const std::string& querytestResponse::_internal_res_info() const {
  return _impl_.res_info_.Get();
}
inline void querytestResponse::_internal_set_res_info(const std::string& value) {
  
  _impl_.res_info_.Set(value, GetArenaForAllocation());
}
inline std::string* querytestResponse::_internal_mutable_res_info() {
  
  return _impl_.res_info_.Mutable(GetArenaForAllocation());
}
inline std::string* querytestResponse::release_res_info() {
  // @@protoc_insertion_point(field_release:querytestResponse.res_info)
  return _impl_.res_info_.Release();
}
inline void querytestResponse::set_allocated_res_info(std::string* res_info) {
  if (res_info != nullptr) {
    
  } else {
    
  }
  _impl_.res_info_.SetAllocated(res_info, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.res_info_.IsDefault()) {
    _impl_.res_info_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:querytestResponse.res_info)
}

// string order_id = 3;
inline void querytestResponse::clear_order_id() {
  _impl_.order_id_.ClearToEmpty();
}
inline const std::string& querytestResponse::order_id() const {
  // @@protoc_insertion_point(field_get:querytestResponse.order_id)
  return _internal_order_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void querytestResponse::set_order_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.order_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:querytestResponse.order_id)
}
inline std::string* querytestResponse::mutable_order_id() {
  std::string* _s = _internal_mutable_order_id();
  // @@protoc_insertion_point(field_mutable:querytestResponse.order_id)
  return _s;
}
inline const std::string& querytestResponse::_internal_order_id() const {
  return _impl_.order_id_.Get();
}
inline void querytestResponse::_internal_set_order_id(const std::string& value) {
  
  _impl_.order_id_.Set(value, GetArenaForAllocation());
}
inline std::string* querytestResponse::_internal_mutable_order_id() {
  
  return _impl_.order_id_.Mutable(GetArenaForAllocation());
}
inline std::string* querytestResponse::release_order_id() {
  // @@protoc_insertion_point(field_release:querytestResponse.order_id)
  return _impl_.order_id_.Release();
}
inline void querytestResponse::set_allocated_order_id(std::string* order_id) {
  if (order_id != nullptr) {
    
  } else {
    
  }
  _impl_.order_id_.SetAllocated(order_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.order_id_.IsDefault()) {
    _impl_.order_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:querytestResponse.order_id)
}

// int32 price = 4;
inline void querytestResponse::clear_price() {
  _impl_.price_ = 0;
}
inline int32_t querytestResponse::_internal_price() const {
  return _impl_.price_;
}
inline int32_t querytestResponse::price() const {
  // @@protoc_insertion_point(field_get:querytestResponse.price)
  return _internal_price();
}
inline void querytestResponse::_internal_set_price(int32_t value) {
  
  _impl_.price_ = value;
}
inline void querytestResponse::set_price(int32_t value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:querytestResponse.price)
}

// string goods = 5;
inline void querytestResponse::clear_goods() {
  _impl_.goods_.ClearToEmpty();
}
inline const std::string& querytestResponse::goods() const {
  // @@protoc_insertion_point(field_get:querytestResponse.goods)
  return _internal_goods();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void querytestResponse::set_goods(ArgT0&& arg0, ArgT... args) {
 
 _impl_.goods_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:querytestResponse.goods)
}
inline std::string* querytestResponse::mutable_goods() {
  std::string* _s = _internal_mutable_goods();
  // @@protoc_insertion_point(field_mutable:querytestResponse.goods)
  return _s;
}
inline const std::string& querytestResponse::_internal_goods() const {
  return _impl_.goods_.Get();
}
inline void querytestResponse::_internal_set_goods(const std::string& value) {
  
  _impl_.goods_.Set(value, GetArenaForAllocation());
}
inline std::string* querytestResponse::_internal_mutable_goods() {
  
  return _impl_.goods_.Mutable(GetArenaForAllocation());
}
inline std::string* querytestResponse::release_goods() {
  // @@protoc_insertion_point(field_release:querytestResponse.goods)
  return _impl_.goods_.Release();
}
inline void querytestResponse::set_allocated_goods(std::string* goods) {
  if (goods != nullptr) {
    
  } else {
    
  }
  _impl_.goods_.SetAllocated(goods, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.goods_.IsDefault()) {
    _impl_.goods_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:querytestResponse.goods)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_test_5fall_2eproto
