/****************************************************

 * query_test.cc
 * 2024-05-08 22:37:24
 * Generated by rpc framework makeService.py
 * Do not edit !!!
****************************************************/


#include "common/log.h"
#include "interface/query_test.h"
#include "pb/test_all.pb.h"

namespace test_all {

QueryTestInterface::QueryTestInterface(const ::querytestRequest& request, ::querytestResponse& response)
  : m_request(request), 
  m_response(response) {

}

QueryTestInterface::~QueryTestInterface() {

}

void QueryTestInterface::run() {
  //
  // Run your business at here
  // m_reponse.set_ret_code(0);
  // m_reponse.set_res_info("Succ");
  //

}


}