/****************************************************

 * business_exception.cc
 * 2024-05-08 22:37:24
 * Generated by rpc framework makeService.py
 * Do not edit !!!
****************************************************/


#pragma once



#include <exception>
#include <string>
#include <memory>
#include <sstream>
#include "common/log.h"



namespace test_all {

class BusinessException : public std::exception {
 public:

  BusinessException(long long code, const std::string& err_info, const std::string& file_name, int line):
      m_error_code(code), m_error_info(err_info), m_file_name(file_name), m_line(line) {

    APPINFOLOG("[%s:%lld] throw BusinessException[code: %d, error info: %s]", file_name.c_str(), line, code, err_info.c_str());
  }

  ~BusinessException() {
  
  }

  const char* what() {
    return m_error_info.c_str();
  }

  std::string error() {
    return m_error_info;
  }

  long long code() {
    return m_error_code;
  }

  std::string file_name() {
    return m_file_name;
  }

  int line() {
    return m_line;
  }

 private:
  long long m_error_code {0};
  std::string m_error_info;

  std::string m_file_name;
  int m_line {0};

};

}