/****************************************************
 * test_all.h
 * 2024-05-08 22:37:24
 * Generated by rpc framework makeService.py
 * Do not edit !!!
****************************************************/




#include <google/protobuf/service.h>
#include <memory>
#include "common/log.h"
#include "common/config.h"
#include "tcp/net_addr.h"
#include "tcp/tcp_server.h"
#include "rpc/rpc_dispatcher.h"
#include "service/test_all.h"

int main(int argc, char* argv[]) {

  if (argc != 2) {
    printf("Start test_all error, argc not 2 \n");
    printf("Start like this: \n");
    printf("./test_all ../conf/rpc.xml \n");
    return 0;
  }

  rpc::Config::SetGlobalConfig(argv[1]);

  rpc::Logger::InitGlobalLogger();

  rpc::RpcDispatcher::GetRpcDispatcher()->registerService(std::make_shared<test_all::TestServiceImpl>());

  rpc::IPNetAddr::s_ptr addr = std::make_shared<rpc::IPNetAddr>("127.0.0.1", rpc::Config::GetGlobalConfig()->m_port);

  rpc::TcpServer tcp_server(addr);

  tcp_server.start();

  return 0;
}