/****************************************************
 * test_all.h
 * 2024-05-08 22:37:24
 * Generated by rpc framework makeService.py
 * Do not edit !!!
****************************************************/


#pragma once

#include <google/protobuf/service.h>
#include "pb/test_all.pb.h"

namespace test_all {

class TestServiceImpl : public TestService {

 public:

  TestServiceImpl() = default;

  ~TestServiceImpl() = default;

  // override from TestService
  virtual void add_test(::google::protobuf::RpcController* controller,
                       const ::addtestRequest* request,
                       ::addtestResponse* response,
                       ::google::protobuf::Closure* done);

  // override from TestService
  virtual void query_test(::google::protobuf::RpcController* controller,
                       const ::querytestRequest* request,
                       ::querytestResponse* response,
                       ::google::protobuf::Closure* done);

  

};

}
