/****************************************************
 * test_all.cc
 * 2024-05-08 22:37:24
 * Generated by rpc framework makeService.py
 * Do not edit !!!
****************************************************/


#include <google/protobuf/service.h>
#include <exception>
#include "common/log.h"
#include "pb/test_all.pb.h"
#include "service/test_all.h"
#include "comm/business_exception.h"
#include "interface/add_test.h"
#include "interface/query_test.h"


#define CALL_RPC_INTERFACE(type)                                                                                                    \
  type impl(*request, *response);                                                                                                   \
  try {                                                                                                                             \
    APPINFOLOG("In|request:{%s}", request->ShortDebugString().c_str());                                                             \
    impl.run();                                                                                                                     \
    response->set_ret_code(0);                                                                                                      \
    response->set_res_info("OK");                                                                                                   \
    APPINFOLOG("Out|response:{%s}", response->ShortDebugString().c_str());                                                          \
    if (done) {                                                                                                                     \
      done->Run();                                                                                                                  \
    }                                                                                                                               \
  } catch (test_all::BusinessException& e) {                                                                                 \
    APPERRORLOG ("[%s:%d] throw BusinessException[error code: %d, error info: %s]",                                                 \
      e.file_name().c_str(), e.line(), e.code(), e.error().c_str());                                                                \
    response->set_ret_code(e.code());                                                                                               \
    response->set_res_info(e.error());                                                                                              \
    APPINFOLOG("Out|response:{%s}", response->ShortDebugString().c_str());                                                          \
    if (done) {                                                                                                                     \
      done->Run();                                                                                                                  \
    }                                                                                                                               \
  } catch (std::exception&) {                                                                                                       \
    APPERRORLOG("occur std::exception, error code = -1, errorinfo = UnKnown error");                                                \
    response->set_ret_code(-1);                                                                                                     \
    response->set_res_info("UnKnown error");                                                                                        \
    APPINFOLOG("Out|response:{%s}", response->ShortDebugString().c_str());                                                          \
    if (done) {                                                                                                                     \
      done->Run();                                                                                                                  \
    }                                                                                                                               \
  } catch (...) {                                                                                                                   \
    APPERRORLOG("occur UnKnown exception, error code = -1, errorinfo = UnKnown error");                                             \
    response->set_ret_code(-1);                                                                                                     \
    response->set_res_info("UnKnown error");                                                                                        \
    APPINFOLOG("Out|response:{%s}", response->ShortDebugString().c_str());                                                          \
    if (done) {                                                                                                                     \
      done->Run();                                                                                                                  \
    }                                                                                                                               \
  }                                                                                                                                 \

namespace test_all {

void TestServiceImpl::add_test(::google::protobuf::RpcController* controller,
                       const ::addtestRequest* request,
                       ::addtestResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(AddTestInterface);
}

void TestServiceImpl::query_test(::google::protobuf::RpcController* controller,
                       const ::querytestRequest* request,
                       ::querytestResponse* response,
                       ::google::protobuf::Closure* done){

  CALL_RPC_INTERFACE(QueryTestInterface);
}



}